# Generated by Django 5.0.1 on 2024-03-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoriesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'product_categories',
            },
        ),
    ]
