# Generated by Django 5.0.1 on 2024-04-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialCategoriesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'raw_material_categories',
            },
        ),
    ]
