# Generated by Django 5.0.1 on 2024-04-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_unitsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementTypesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'movement_types',
            },
        ),
    ]
