# Generated by Django 5.0.1 on 2024-04-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_salesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmodel',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
