# Generated by Django 5.0.1 on 2024-04-09 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_salesmodel_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('price', models.FloatField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('id_product_categories', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.productcategoriesmodel')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
