# Generated by Django 5.0.1 on 2024-04-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_salesmodel_name_productsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsmodel',
            old_name='id_product_categories',
            new_name='product_categories',
        ),
    ]
