# Generated by Django 5.0.1 on 2024-04-09 17:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_id_product_categories_productsmodel_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('price', models.FloatField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('raw_material_categories', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.rawmaterialcategoriesmodel')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.unitsmodel')),
            ],
            options={
                'db_table': 'raw_materials',
            },
        ),
        migrations.CreateModel(
            name='InventaryRawMaterialsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('date_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_exp', models.DateTimeField()),
                ('movement_types', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.movementtypesmodel')),
                ('raw_materials', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.rawmaterialsmodel')),
            ],
            options={
                'db_table': 'inventary_raw_materials',
            },
        ),
    ]
