# Generated by Django 5.0.1 on 2024-04-11 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rawmaterialsmodel_inventaryrawmaterialsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsMateriaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.productsmodel')),
                ('raw_materials', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.rawmaterialsmodel')),
            ],
            options={
                'db_table': 'products_materia',
            },
        ),
    ]
