# Generated by Django 5.0.1 on 2024-04-11 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_productsmateriamodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailSalesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0)),
                ('date_reg', models.DateTimeField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.productsmodel')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.salesmodel')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'detail/sales',
            },
        ),
    ]
