# Generated by Django 5.0.1 on 2024-04-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_detailsalesmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventaryRawMaterialsModel',
            new_name='InventoryRawMaterialsModel',
        ),
        migrations.RenameModel(
            old_name='ProductsMateriaModel',
            new_name='ProductsMaterialsModel',
        ),
        migrations.AlterModelTable(
            name='detailsalesmodel',
            table='detail_sales',
        ),
        migrations.AlterModelTable(
            name='inventoryrawmaterialsmodel',
            table='inventory_raw_materials',
        ),
        migrations.AlterModelTable(
            name='productsmaterialsmodel',
            table='products_materials',
        ),
    ]
