# Generated by Django 5.0.1 on 2024-04-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_inventaryrawmaterialsmodel_inventoryrawmaterialsmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrawmaterialsmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
