# Generated by Django 5.0.1 on 2024-05-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_inventoryrawmaterialsmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
