# Generated by Django 5.0.1 on 2024-05-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_productsmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmaterialsmodel',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
