# Generated by Django 5.0.1 on 2024-05-19 02:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_productsmaterialsmodel_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsalesmodel',
            name='date_reg',
        ),
        migrations.RemoveField(
            model_name='detailsalesmodel',
            name='users',
        ),
        migrations.AddField(
            model_name='detailsalesmodel',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salesmodel',
            name='date_reg',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salesmodel',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
